//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoonkieMonkey.Resx {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoonkieMonkey.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bogotá:.
        /// </summary>
        internal static string BogotaText {
            get {
                return ResourceManager.GetString("BogotaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boston Scientific Group.
        /// </summary>
        internal static string BscText {
            get {
                return ResourceManager.GetString("BscText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BSJI.
        /// </summary>
        internal static string BSJIText {
            get {
                return ResourceManager.GetString("BSJIText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Project.
        /// </summary>
        internal static string CardButtonText {
            get {
                return ResourceManager.GetString("CardButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Give the Hability to the content administrator to create, edit, and delete the desired commercial content in a technological solution, and allow the users to download and work online or offline with the content, were the two main challenges we had..
        /// </summary>
        internal static string CardDescription {
            get {
                return ResourceManager.GetString("CardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Digital Platform for Pfizer.
        /// </summary>
        internal static string CardTitle {
            get {
                return ResourceManager.GetString("CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I need you to build an application.
        /// </summary>
        internal static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I want a quote.
        /// </summary>
        internal static string EmailSubjet {
            get {
                return ResourceManager.GetString("EmailSubjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Harpenden, UK:.
        /// </summary>
        internal static string HarpendenText {
            get {
                return ResourceManager.GetString("HarpendenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Let’s work together!.
        /// </summary>
        internal static string LastFrameTitle {
            get {
                return ResourceManager.GetString("LastFrameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get in Touch!.
        /// </summary>
        internal static string MainFrameButton {
            get {
                return ResourceManager.GetString("MainFrameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We are samurais code monkeys that masters the most recent data security protocols, encrypted methodologies and Blockchain development..
        /// </summary>
        internal static string MainFrameDescription {
            get {
                return ResourceManager.GetString("MainFrameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expert Samurais on Develop Secure apps with Sensitive data..
        /// </summary>
        internal static string MainFrameTitle {
            get {
                return ResourceManager.GetString("MainFrameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miami, USA:.
        /// </summary>
        internal static string MiamiText {
            get {
                return ResourceManager.GetString("MiamiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Case studies.
        /// </summary>
        internal static string MiddleFrameTitle {
            get {
                return ResourceManager.GetString("MiddleFrameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pfizer.
        /// </summary>
        internal static string PfizerText {
            get {
                return ResourceManager.GetString("PfizerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Takeda.
        /// </summary>
        internal static string TakedaText {
            get {
                return ResourceManager.GetString("TakedaText", resourceCulture);
            }
        }
    }
}
