//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoonkieMonkey.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoonkieMonkey.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bogotá:.
        /// </summary>
        internal static string BogotaText {
            get {
                return ResourceManager.GetString("BogotaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boston Scientific Group.
        /// </summary>
        internal static string BscText {
            get {
                return ResourceManager.GetString("BscText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSJI.
        /// </summary>
        internal static string BSJIText {
            get {
                return ResourceManager.GetString("BSJIText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Project.
        /// </summary>
        internal static string CardButtonText {
            get {
                return ResourceManager.GetString("CardButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the Hability to the content administrator to create, edit, and delete the desired commercial content in a technological solution, and allow the users to download and work online or offline with the content, were the two main challenges we had..
        /// </summary>
        internal static string CardDescription {
            get {
                return ResourceManager.GetString("CardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Platform for Pfizer.
        /// </summary>
        internal static string CardTitle {
            get {
                return ResourceManager.GetString("CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need you to build an application.
        /// </summary>
        internal static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want a quote.
        /// </summary>
        internal static string EmailSubjet {
            get {
                return ResourceManager.GetString("EmailSubjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Don&apos;t Find Users or you&apos;re not conectec to the internet, Please Try Again Later.
        /// </summary>
        internal static string EmpyUsers {
            get {
                return ResourceManager.GetString("EmpyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harpenden, UK:.
        /// </summary>
        internal static string HarpendenText {
            get {
                return ResourceManager.GetString("HarpendenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s work together!.
        /// </summary>
        internal static string LastFrameTitle {
            get {
                return ResourceManager.GetString("LastFrameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in Touch!.
        /// </summary>
        internal static string MainFrameButton {
            get {
                return ResourceManager.GetString("MainFrameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are samurais code monkeys that masters the most recent data security protocols, encrypted methodologies and Blockchain development..
        /// </summary>
        internal static string MainFrameDescription {
            get {
                return ResourceManager.GetString("MainFrameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert Samurais on Develop Secure apps with Sensitive data..
        /// </summary>
        internal static string MainFrameTitle {
            get {
                return ResourceManager.GetString("MainFrameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miami, USA:.
        /// </summary>
        internal static string MiamiText {
            get {
                return ResourceManager.GetString("MiamiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case studies.
        /// </summary>
        internal static string MiddleFrameTitle {
            get {
                return ResourceManager.GetString("MiddleFrameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfizer.
        /// </summary>
        internal static string PfizerText {
            get {
                return ResourceManager.GetString("PfizerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeda.
        /// </summary>
        internal static string TakedaText {
            get {
                return ResourceManager.GetString("TakedaText", resourceCulture);
            }
        }
    }
}
